# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84d62c34a80c8b74789dddafcf917f9ce5ea21dc2130850576473b307b6353aa4efbc9f694efaee9e7b9cf838aeec14ee577fbcf69bf2ba50daca5210ec3be5b

test:
  secret_key_base: 32311d6cb0bd3d6ada7c766ab5c7b64fe46bb69becfb8ced36aea26db02cac9bb7ec88de1b8e910c74915788f19a490d4421ef092c070ec2db5d748837b3fb1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
